# Generated by Django 4.0.6 on 2022-08-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_companies_options_alter_account_role_and_more'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_fair_name', models.CharField(max_length=100)),
                ('conducted_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobFairRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerd_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companies')),
                ('jobfair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.jobfair')),
            ],
        ),
        migrations.AddField(
            model_name='jobfair',
            name='company',
            field=models.ManyToManyField(through='admins.JobFairRegister', to='accounts.companies'),
        ),
    ]
