# Generated by Django 4.0.6 on 2022-08-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_count_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='view_count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.count'),
        ),
    ]
