# Generated by Django 4.0.6 on 2022-08-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='view_count',
        ),
        migrations.AddField(
            model_name='count',
            name='viewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='count',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
