# Generated by Django 4.0.6 on 2022-08-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_intrestes_intrests_intrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
