# Generated by Django 4.0.6 on 2022-08-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_count_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
