# Generated by Django 4.0.6 on 2022-08-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobs_created_jobs_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(choices=[('ParTime', 'PRTIME'), ('FullTime', 'FULLTIME'), ('Intership', 'INTERNSHIP')]),
        ),
    ]
