# Generated by Django 4.0.6 on 2022-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_jobs_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('ParTime', 'PRTIME'), ('FullTime', 'FULLTIME'), ('Intership', 'INTERNSHIP')], default='FullTime', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(),
        ),
    ]
