# Generated by Django 4.0.6 on 2022-08-11 14:07

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_spamcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='resume',
            field=models.FileField(upload_to='pdfs/', validators=[home.models.validate_file_extension]),
        ),
    ]
