# Generated by Django 4.0.6 on 2022-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_appliedjobs_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamcompanies',
            name='reason',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
