# Generated by Django 4.0.6 on 2022-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_spamcompanies_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
